CREATE USER 'beer'@'localhost' IDENTIFIED BY 'cerveza';

GRANT USAGE ON * . * TO 'beer'@'localhost' IDENTIFIED BY 'cerveza' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

CREATE DATABASE `beer` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `beer` . * TO 'beer'@'localhost' WITH GRANT OPTION;

